version: '3'
services:
  vault:
    image: vault
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=s.wZVv7OZ31L621d7KFYHOfhQg
    ports:
      - 8200:8200
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    ports:
      - 3306:3306